# -*- coding: utf-8 -*-
"""Food_recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iT1Sy8CNDOHZRh-7IT1pbv1ebpoNWbFe
"""

import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D, Input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
import numpy as np
import os

# THIẾT LẬP ĐƯỜNG DẪN
train_dir = "/content/drive/MyDrive/Vienamese_Dishes"
model_save_path = "/content/drive/MyDrive/food_recognition_model.h5"
class_indices_path = "/content/drive/MyDrive/food_class_indices.npy"

img_width, img_height = 224, 224
batch_size = 16
NUM_CLASSES = 5

# TIỀN XỬ LÝ + TĂNG CƯỜNG DỮ LIỆU
train_datagen = ImageDataGenerator(
    rescale=1.0/255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.15,
    zoom_range=0.2,
    horizontal_flip=True,
    vertical_flip=False,
    brightness_range=[0.7, 1.3],
    fill_mode="nearest",
    validation_split=0.2
)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode="categorical",
    subset='training',
    shuffle=True,
    seed=42
)

validation_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode="categorical",
    subset='validation',
    shuffle=False,
    seed=42
)
NUM_CLASSES = train_generator.num_classes

np.save(class_indices_path, train_generator.class_indices)
print("Các lớp đã phát hiện:", train_generator.class_indices)
print(f"Tổng ảnh training:    {train_generator.samples}")
print(f"Tổng ảnh validation:  {validation_generator.samples}")
print(f"Số lượng lớp:         {NUM_CLASSES}")

# XÂY DỰNG MÔ HÌNH
base_model =MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(img_width, img_height, 3)
)

base_model.trainable = False

inputs = Input(shape=(img_width, img_height, 3))
x = base_model(inputs, training=False)
x = GlobalAveragePooling2D()(x)
x = Dense(64, activation='relu')(x)
x = Dropout(0.5)(x)
outputs = Dense(NUM_CLASSES, activation='softmax')(x)
model = Model(inputs, outputs)
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)
model.summary()

# CALLBACKS
callbacks = [
    EarlyStopping(
        monitor='val_accuracy',
        patience=12,
        restore_best_weights=True,
        verbose=1
    ),
    ModelCheckpoint(
        model_save_path,
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=5,
        min_lr=1e-7,
        verbose=1
    )
]

# GIAI ĐOẠN 1: Huấn luyện phần đầu
print("\n=== GIAI ĐOẠN 1: Huấn luyện classifier ===")
steps_per_epoch  = max(1, train_generator.samples // batch_size)
validation_steps = max(1, validation_generator.samples // batch_size)

history1 = model.fit(
    train_generator,
    steps_per_epoch=steps_per_epoch,
    epochs=30,
    validation_data=validation_generator,
    validation_steps=validation_steps,
    callbacks=callbacks
)

# GIAI ĐOẠN 2: Fine-tuning
print("\n=== GIAI ĐOẠN 2: Fine-tuning ===")
base_model.trainable = True

for layer in base_model.layers[:-10]:
    layer.trainable = False

model.compile(
    optimizer=Adam(learning_rate=0.00001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history2 = model.fit(
    train_generator,
    steps_per_epoch=steps_per_epoch,
    epochs=20,
    validation_data=validation_generator,
    validation_steps=validation_steps,
    callbacks=callbacks
)

# VẼ BIỂU ĐỒ KẾT QUẢ
acc     = history1.history['accuracy']     + history2.history['accuracy']
val_acc = history1.history['val_accuracy'] + history2.history['val_accuracy']
loss    = history1.history['loss']         + history2.history['loss']
val_loss= history1.history['val_loss']     + history2.history['val_loss']

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(acc,     label='Train Accuracy')
plt.plot(val_acc, label='Val Accuracy')
plt.xlabel('Epoch'); plt.ylabel('Accuracy')
plt.title('Độ chính xác qua các epoch')
plt.legend()

plt.subplot(1, 2, 2)
loss = history1.history['loss'] + history2.history['loss']
val_loss = history1.history['val_loss'] + history2.history['val_loss']
plt.plot(loss, label='Train Loss')
plt.plot(val_loss, label='Val Loss')
plt.xlabel('Epoch'); plt.ylabel('Loss')
plt.title('Loss'); plt.legend()
plt.tight_layout(); plt.show()

print(f"\n✅ Model đã lưu tại: {model_save_path}")

# PHẦN 2: KIỂM TRA ĐƠN LẺ
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import load_img
import numpy as np
import matplotlib.pyplot as plt


model_save_path    = "/content/drive/MyDrive/food_recognition_model.h5"
class_indices_path = "/content/drive/MyDrive/food_class_indices.npy"
img_width, img_height = 224, 224
CONFIDENCE_THRESHOLD  = 0.5

# Load model và class indices
model = load_model(model_save_path)
class_indices = np.load(class_indices_path, allow_pickle=True).item()
class_labels  = {v: k for k, v in class_indices.items()}

def predict_food(path):

    img = load_img(path, target_size=(img_width, img_height))
    plt.imshow(img); plt.axis('off'); plt.show()

    img_array = np.array(img) / 255.0
    img_array = img_array.reshape(1, img_width, img_height, 3)

    predictions = model.predict(img_array, verbose=0)[0]
    top_idx     = np.argmax(predictions)
    confidence  = predictions[top_idx]
    food_name   = class_labels[top_idx]
    print(f"Món ăn tiên đoán: {food_name}")

# CHẠY THỬ - Thay đường dẫn ảnh vào đây
test_path = '/content/drive/MyDrive/Vienamese_Dishes/Com_tam/Authentic Cơm Tấm Sườn Bì Chả Trứng.jpg'
predict_food(test_path)

# WEB APP - Nhận Diện Món Ăn Việt Nam

!pip install flask flask-cors pyngrok pillow tensorflow -q

from flask import Flask, request, jsonify
from flask_cors import CORS
from pyngrok import ngrok
import tensorflow as tf
import numpy as np
from PIL import Image
import base64, io

app = Flask(__name__)
CORS(app)

# Load model
model = tf.keras.models.load_model("/content/drive/MyDrive/food_recognition_model.h5")
class_indices = np.load("/content/drive/MyDrive/food_class_indices.npy", allow_pickle=True).item()
class_labels = {v: k for k, v in class_indices.items()}

IMG_SIZE = 224
THRESHOLD = 0.5

def preprocess(image_data):
    if ',' in image_data:
        image_data = image_data.split(',')[1]
    img_bytes = base64.b64decode(image_data)
    img = Image.open(io.BytesIO(img_bytes)).convert('RGB')
    img = img.resize((IMG_SIZE, IMG_SIZE))
    arr = np.array(img) / 255.0
    return arr.reshape(1, IMG_SIZE, IMG_SIZE, 3)

@app.route('/')
def index():
    return HTML_PAGE

@app.route('/predict', methods=['POST'])
def predict():
    try:
        data = request.json
        arr = preprocess(data['image'])
        preds = model.predict(arr, verbose=0)[0]
        top_idx = int(np.argmax(preds))
        confidence = float(preds[top_idx])
        top3 = [{"name": class_labels[int(i)], "confidence": float(preds[int(i)])}
                for i in np.argsort(preds)[-5:][::-1]]
        return jsonify({
            "name": class_labels[top_idx] if confidence >= THRESHOLD else "Không nhận ra",
            "confidence": confidence,
            "is_known": confidence >= THRESHOLD,
            "top3": top3
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

HTML_PAGE = '''<!DOCTYPE html>
<html lang="vi">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>🍜 Nhận Diện Món Ăn Việt</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@300;400;500;600;700&display=swap');
  *{margin:0;padding:0;box-sizing:border-box;}
  body{font-family:'Be Vietnam Pro',sans-serif;background:#fdf6ee;color:#3d2b1f;min-height:100vh;}

  /* HEADER */
  .header{background:linear-gradient(135deg,#ff6b35,#f7931e,#ffcd3c);padding:28px 20px;text-align:center;position:relative;overflow:hidden;}
  .header::before{content:'🍜 🍲 🥗 🍱 🍛 🥘 🍜 🍲';position:absolute;top:8px;left:0;right:0;font-size:20px;opacity:0.2;letter-spacing:12px;}
  .header::after{content:'🍜 🍲 🥗 🍱 🍛 🥘 🍜 🍲';position:absolute;bottom:8px;left:0;right:0;font-size:20px;opacity:0.2;letter-spacing:12px;}
  .header h1{font-size:32px;font-weight:700;color:#fff;text-shadow:0 2px 8px rgba(0,0,0,0.2);}
  .header p{color:rgba(255,255,255,0.9);margin-top:6px;font-size:15px;}

  /* LAYOUT */
  .container{max-width:900px;margin:30px auto;padding:0 20px;}

  /* TABS */
  .tabs{display:flex;gap:12px;margin-bottom:24px;}
  .tab{flex:1;padding:14px;border:2px solid #e8d5c0;border-radius:14px;background:#fff;cursor:pointer;font-family:'Be Vietnam Pro',sans-serif;font-size:15px;font-weight:600;color:#a0856b;transition:all 0.3s;text-align:center;}
  .tab.active{background:linear-gradient(135deg,#ff6b35,#f7931e);border-color:transparent;color:#fff;box-shadow:0 6px 20px rgba(255,107,53,0.35);}
  .tab:hover:not(.active){border-color:#f7931e;color:#f7931e;transform:translateY(-2px);}

  /* PANELS */
  .panel{display:none;background:#fff;border-radius:20px;padding:28px;border:1.5px solid #f0ddd0;box-shadow:0 4px 24px rgba(255,107,53,0.08);}
  .panel.active{display:block;animation:fadeUp 0.4s ease;}
  @keyframes fadeUp{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}

  /* UPLOAD AREA */
  .upload-area{border:2.5px dashed #f7b46a;border-radius:16px;padding:50px 20px;text-align:center;cursor:pointer;transition:all 0.3s;background:#fffaf5;position:relative;}
  .upload-area:hover,.upload-area.dragover{border-color:#ff6b35;background:#fff3eb;transform:scale(1.01);}
  .upload-icon{font-size:52px;margin-bottom:12px;}
  .upload-area p{color:#a0856b;font-size:15px;margin-top:6px;}
  .upload-area strong{color:#ff6b35;}
  #fileInput{display:none;}
  .preview-img{max-width:100%;max-height:320px;border-radius:12px;margin:16px auto;display:block;box-shadow:0 4px 16px rgba(0,0,0,0.1);}

  /* CAMERA */
  .camera-wrapper{position:relative;border-radius:16px;overflow:hidden;background:#1a1a1a;max-width:520px;margin:0 auto;}
  video{width:100%;display:block;border-radius:16px;}
  .camera-overlay{position:absolute;inset:0;pointer-events:none;}
  .scan-frame{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);width:220px;height:220px;border:3px solid rgba(255,107,53,0.8);border-radius:16px;}
  .scan-frame::before,.scan-frame::after{content:'';position:absolute;width:24px;height:24px;border-color:#ff6b35;border-style:solid;}
  .scan-frame::before{top:-3px;left:-3px;border-width:4px 0 0 4px;border-radius:4px 0 0 0;}
  .scan-frame::after{bottom:-3px;right:-3px;border-width:0 4px 4px 0;border-radius:0 0 4px 0;}
  .scan-line{position:absolute;left:10%;right:10%;height:2px;background:linear-gradient(90deg,transparent,#ff6b35,transparent);animation:scanMove 2s ease-in-out infinite;display:none;}
  .scanning .scan-line{display:block;}
  @keyframes scanMove{0%,100%{top:15%}50%{top:85%}}

  /* BUTTONS */
  .btn-group{display:flex;gap:10px;justify-content:center;margin-top:18px;flex-wrap:wrap;}
  .btn{padding:12px 24px;border:none;border-radius:12px;font-family:'Be Vietnam Pro',sans-serif;font-size:14px;font-weight:600;cursor:pointer;transition:all 0.3s;}
  .btn-main{background:linear-gradient(135deg,#ff6b35,#f7931e);color:#fff;box-shadow:0 4px 16px rgba(255,107,53,0.3);}
  .btn-main:hover{transform:translateY(-2px);box-shadow:0 8px 24px rgba(255,107,53,0.4);}
  .btn-outline{background:#fff;border:2px solid #f7b46a;color:#f7931e;}
  .btn-outline:hover{background:#fff8f0;transform:translateY(-2px);}
  .btn-red{background:linear-gradient(135deg,#ff4757,#ff6b81);color:#fff;}
  .btn-red:hover{transform:translateY(-2px);}
  .btn:disabled{opacity:0.45;cursor:not-allowed;transform:none!important;}

  /* RESULT */
  .result-box{background:linear-gradient(135deg,#fff8f0,#fff3e6);border:1.5px solid #f7b46a;border-radius:18px;padding:24px;margin-top:24px;display:none;animation:fadeUp 0.5s ease;}
  .result-box.show{display:block;}
  .result-emoji{font-size:56px;text-align:center;margin-bottom:10px;}
  .result-name{font-size:26px;font-weight:700;text-align:center;color:#d84315;}
  .result-sub{text-align:center;color:#a0856b;margin:6px 0 14px;}
  .conf-bar-wrap{background:#f0ddd0;border-radius:30px;height:12px;overflow:hidden;margin:8px 0 16px;}
  .conf-bar{height:100%;border-radius:30px;transition:width 1s ease;background:linear-gradient(90deg,#ff6b35,#ffcd3c);}
  .conf-bar.low{background:linear-gradient(90deg,#aaa,#ccc);}
  .top3{margin-top:12px;}
  .top3-title{font-size:13px;color:#a0856b;font-weight:600;margin-bottom:8px;}
  .top3-item{display:flex;align-items:center;justify-content:space-between;padding:8px 14px;background:#fff;border-radius:10px;margin-bottom:6px;border:1px solid #f0ddd0;font-size:14px;}
  .top3-pct{font-weight:700;color:#ff6b35;}

  /* LOADING */
  .loading{display:none;text-align:center;padding:28px;}
  .loading.show{display:block;}
  .bowl-spin{font-size:44px;animation:spin 0.9s linear infinite;display:inline-block;}
  @keyframes spin{to{transform:rotate(360deg)}}
  .loading p{margin-top:10px;color:#a0856b;font-weight:500;}

  /* HISTORY */
  .history-section{margin-top:28px;background:#fff;border-radius:20px;padding:24px;border:1.5px solid #f0ddd0;}
  .history-title{font-size:17px;font-weight:700;color:#d84315;margin-bottom:14px;display:flex;justify-content:space-between;align-items:center;}
  .history-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(130px,1fr));gap:12px;}
  .history-card{background:#fff8f0;border-radius:12px;padding:12px;text-align:center;border:1px solid #f0ddd0;transition:all 0.2s;}
  .history-card:hover{transform:translateY(-3px);box-shadow:0 6px 16px rgba(255,107,53,0.15);}
  .history-card img{width:70px;height:70px;object-fit:cover;border-radius:8px;margin-bottom:6px;}
  .history-card .hname{font-size:12px;font-weight:600;color:#3d2b1f;line-height:1.3;}
  .history-card .hconf{font-size:11px;color:#f7931e;font-weight:600;}
  .empty-history{text-align:center;color:#c4a88e;padding:20px;font-size:14px;}

  /* FOOD TIPS */
  .food-tip{background:linear-gradient(135deg,#fff8f0,#ffeedd);border-left:4px solid #f7931e;border-radius:0 12px 12px 0;padding:14px 18px;margin-top:20px;font-size:14px;color:#7a5c44;display:none;}
  .food-tip.show{display:block;animation:fadeUp 0.4s ease;}
  .food-tip strong{color:#d84315;}
</style>
</head>
<body>
<div class="header">
  <h1>🍜 Nhận Diện Món Ăn Việt</h1>
  <p>Chụp hoặc tải ảnh lên để khám phá món ăn</p>
</div>

<div class="container">
  <!-- TABS -->
  <div class="tabs">
    <button class="tab active" onclick="switchTab('upload')">📁 Tải Ảnh Lên</button>
    <button class="tab" onclick="switchTab('camera')">📷 Chụp Trực Tiếp</button>
  </div>

  <!-- PANEL UPLOAD -->
  <div class="panel active" id="panel-upload">
    <div class="upload-area" id="uploadArea" onclick="document.getElementById('fileInput').click()" ondragover="onDrag(event,true)" ondragleave="onDrag(event,false)" ondrop="onDrop(event)">
      <div class="upload-icon">🖼️</div>
      <p><strong>Nhấn để chọn ảnh</strong> hoặc kéo thả vào đây</p>
      <p>Hỗ trợ JPG, PNG, WEBP</p>
    </div>
    <input type="file" id="fileInput" accept="image/*" onchange="onFileSelect(event)">
    <img id="uploadPreview" class="preview-img" style="display:none">
    <div class="btn-group">
      <button class="btn btn-main" id="uploadPredictBtn" onclick="predictUpload()" disabled>🔍 Nhận Diện</button>
      <button class="btn btn-outline" onclick="clearUpload()">🗑 Xóa</button>
    </div>
  </div>

  <!-- PANEL CAMERA -->
  <div class="panel" id="panel-camera">
    <div class="camera-wrapper" id="cameraWrapper">
      <video id="video" autoplay muted playsinline></video>
      <div class="camera-overlay">
        <div class="scan-frame"></div>
        <div class="scan-line" id="scanLine"></div>
      </div>
    </div>
    <div class="btn-group">
      <button class="btn btn-main" id="startCamBtn" onclick="startCamera()">📷 Bật Camera</button>
      <button class="btn btn-outline" id="snapBtn" onclick="snapAndPredict()" disabled>🍽 Nhận Diện</button>
      <button class="btn btn-red" id="stopCamBtn" onclick="stopCamera()" disabled>⏹ Tắt</button>
    </div>
    <canvas id="camCanvas" style="display:none"></canvas>
  </div>

  <!-- LOADING -->
  <div class="loading" id="loading">
    <div class="bowl-spin">🍜</div>
    <p>Đang phân tích món ăn...</p>
  </div>

  <!-- RESULT -->
  <div class="result-box" id="resultBox">
    <div class="result-emoji" id="resEmoji">🍽</div>
    <div class="result-name" id="resName">—</div>
    <div class="result-sub" id="resSub">—</div>
    <div class="conf-bar-wrap"><div class="conf-bar" id="confBar" style="width:0%"></div></div>
    <div class="top3" id="top3"></div>
  </div>

  <!-- FOOD TIP -->
  <div class="food-tip" id="foodTip"></div>

  <!-- HISTORY -->
  <div class="history-section">
    <div class="history-title">
      <span>🕐 Lịch Sử Nhận Diện</span>
      <button class="btn btn-outline" style="padding:6px 14px;font-size:13px" onclick="clearHistory()">Xóa</button>
    </div>
    <div class="history-grid" id="historyGrid">
      <div class="empty-history">Chưa có lịch sử nào 🍽</div>
    </div>
  </div>
</div>

<script>
const FOOD_TIPS = {
  "Com_tam":    "🍚 Cơm Tấm — đặc sản Sài Gòn với cơm gạo tấm, sườn nướng, bì, chả và trứng ốp la!",
  "Banh_mi":    "🥖 Bánh Mì — món ăn đường phố Việt nổi tiếng thế giới, vỏ giòn nhân thơm!",
  "Pho":        "🍜 Phở — linh hồn ẩm thực Việt, nước dùng ninh xương bò hàng giờ thơm ngát!",
  "Bun_bo_Hue": "🌶 Bún Bò Huế — đậm đà cay nồng, đặc sản xứ Huế không thể bỏ qua!",
  "Goi_cuon":   "🥗 Gỏi Cuốn — thanh mát, lành mạnh với tôm thịt rau củ cuốn bánh tráng tươi!"
};

let uploadBase64 = null;
let camStream = null;
let historyItems = [];

// ---- TABS ----
function switchTab(tab) {
  document.querySelectorAll('.tab').forEach((t,i)=>t.classList.toggle('active',['upload','camera'][i]===tab));
  document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));
  document.getElementById('panel-'+tab).classList.add('active');
  hideResult();
}

// ---- UPLOAD ----
function onDrag(e,over){e.preventDefault();document.getElementById('uploadArea').classList.toggle('dragover',over);}
function onDrop(e){e.preventDefault();onDrag(e,false);const f=e.dataTransfer.files[0];if(f)loadFile(f);}
function onFileSelect(e){const f=e.target.files[0];if(f)loadFile(f);}
function loadFile(file){
  const reader=new FileReader();
  reader.onload=ev=>{
    uploadBase64=ev.target.result;
    const img=document.getElementById('uploadPreview');
    img.src=uploadBase64;img.style.display='block';
    document.getElementById('uploadPredictBtn').disabled=false;
  };
  reader.readAsDataURL(file);
}
function clearUpload(){
  uploadBase64=null;
  document.getElementById('uploadPreview').style.display='none';
  document.getElementById('fileInput').value='';
  document.getElementById('uploadPredictBtn').disabled=true;
  hideResult();
}
async function predictUpload(){
  if(!uploadBase64)return;
  await runPredict(uploadBase64);
}

// ---- CAMERA ----
async function startCamera(){
  try{
    camStream=await navigator.mediaDevices.getUserMedia({video:{width:640,height:480,facingMode:'environment'},audio:false});
    document.getElementById('video').srcObject=camStream;
    document.getElementById('snapBtn').disabled=false;
    document.getElementById('stopCamBtn').disabled=false;
    document.getElementById('startCamBtn').disabled=true;
  }catch(e){alert('Không thể mở camera: '+e.message);}
}
function stopCamera(){
  if(camStream)camStream.getTracks().forEach(t=>t.stop());
  camStream=null;
  document.getElementById('video').srcObject=null;
  document.getElementById('snapBtn').disabled=true;
  document.getElementById('stopCamBtn').disabled=true;
  document.getElementById('startCamBtn').disabled=false;
  document.getElementById('cameraWrapper').classList.remove('scanning');
}
async function snapAndPredict(){
  const video=document.getElementById('video');
  const canvas=document.getElementById('camCanvas');
  canvas.width=video.videoWidth||640;
  canvas.height=video.videoHeight||480;
  canvas.getContext('2d').drawImage(video,0,0);
  const img64=canvas.toDataURL('image/jpeg',0.85);
  document.getElementById('cameraWrapper').classList.add('scanning');
  await runPredict(img64);
  setTimeout(()=>document.getElementById('cameraWrapper').classList.remove('scanning'),1200);
}

// ---- PREDICT ----
async function runPredict(imageData){
  document.getElementById('loading').classList.add('show');
  hideResult();
  try{
    const resp=await fetch('/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:imageData})});
    const data=await resp.json();
    showResult(data,imageData);
  }catch(e){alert('Lỗi kết nối server: '+e);}
  finally{document.getElementById('loading').classList.remove('show');}
}

function showResult(data,thumb){
  const box=document.getElementById('resultBox');
  box.classList.add('show');
  document.getElementById('resEmoji').textContent=data.is_known?'✅':'❓';
  document.getElementById('resName').textContent=data.name;
  document.getElementById('resSub').textContent=`Độ tin cậy: ${(data.confidence*100).toFixed(1)}%`;
  const bar=document.getElementById('confBar');
  bar.style.width=(data.confidence*100)+'%';
  bar.className='conf-bar'+(data.is_known?'':' low');
  // top3
  let h='<div class="top3-title">🏆 Top 5 dự đoán</div>';
  const medals=['🥇','🥈','🥉','4️⃣','5️⃣'];
  data.top3.forEach((p,i)=>{
    h+=`<div class="top3-item"><span>${medals[i]} ${p.name}</span><span class="top3-pct">${(p.confidence*100).toFixed(1)}%</span></div>`;
  });
  document.getElementById('top3').innerHTML=h;
  // food tip
  const tip=document.getElementById('foodTip');
  const tipText=FOOD_TIPS[data.name];
  if(tipText&&data.is_known){tip.innerHTML='<strong>💡 Thú vị:</strong> '+tipText;tip.classList.add('show');}
  else{tip.classList.remove('show');}
  // history
  addHistory(data,thumb);
}

function hideResult(){
  document.getElementById('resultBox').classList.remove('show');
  document.getElementById('foodTip').classList.remove('show');
}

// ---- HISTORY ----
function addHistory(data,thumb){
  historyItems.unshift({name:data.name,confidence:data.confidence,thumb,known:data.is_known});
  if(historyItems.length>12)historyItems.pop();
  renderHistory();
}
function renderHistory(){
  const grid=document.getElementById('historyGrid');
  if(!historyItems.length){grid.innerHTML='<div class="empty-history">Chưa có lịch sử nào 🍽</div>';return;}
  grid.innerHTML=historyItems.map(item=>`
    <div class="history-card">
      <img src="${item.thumb}" alt="${item.name}">
      <div class="hname">${item.name}</div>
      <div class="hconf">${item.known?'✓':''} ${(item.confidence*100).toFixed(0)}%</div>
    </div>`).join('');
}
function clearHistory(){historyItems=[];renderHistory();}
</script>
</body>
</html>'''

# KHỞI CHẠY SERVER
port = 5000
ngrok.set_auth_token("3EIjTVTxeW3WKxOMqhh9fdmZ3pY_7duYVRnmZNmg8MHt5wKn")
public_url = ngrok.connect(port)
print(f"\n{'='*50}")
print(f"🚀 Web App đang chạy!")
print(f"🌐 Link: {public_url}")
print(f"📱 Mở link trên trình duyệt để dùng!")
print(f"{'='*50}")
app.run(port=port, use_reloader=False)